import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sileo";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${font.className} antialiased`}>
        <NextTopLoader color="#2563eb" />
        <div className="fixed top-0 z-1000">
          <Toaster
            position="top-center"
            theme="light"
            options={{
              styles: {
                description: "text-white/75!",
              },
              roundness: 12,
            }}
          />
        </div>

        {children}
      </body>
    </html>
  );
}
