export const jobCategories = [
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Product Management",
  "Data Science",
  "Artificial Intelligence",
  "Cyber Security",
  "DevOps & Cloud",
  "IT Support",
  "Networking",
  "Game Development",
  "Quality Assurance (QA)",
  "Digital Marketing",
  "Content Writing",
  "SEO",
  "Social Media Management",
  "Graphic Design",
  "Video Editing",
  "Sales",
  "Business Development",
  "Customer Support",
  "Human Resources (HR)",
  "Finance & Accounting",
  "Legal",
  "Project Management",
  "Operations",
  "Supply Chain",
  "Education & Training",
  "Healthcare",
  "Engineering",
  "Construction",
  "Hospitality & Tourism",
  "Administrative",
  "Translation",
  "Freelance & Remote",
];
